on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build with Emscripten
      uses: ./.github/actions/build-with-emscripten
    - name: Create package
      run: npm pack
    - name: Get package infos
      run: echo "##[set-output name=name;]$(npm pack --dry-run 2> /dev/null)"
      id: package_infos
    - name: Test use of infos
      run: |
        echo ${FOO}
        ls -l
      env:
        FOO: ${{ steps.package_infos.outputs.name }}
