on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build with Emscripten
      uses: ./.github/actions/build-with-emscripten
    - name: List
      run: |
        ls -l
        echo '#####'
        ls -l dist
